apiVersion: v1
kind: Service
metadata:
  name: grpc
spec:
  type: {{ .Values.grpc.service.type }}
  selector:
    app: grpc
  ports:
    - port: {{ .Values.grpc.service.port }}
      targetPort: {{ .Values.grpc.service.port }}