apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
spec:
  replicas: {{ .Values.grpc.replicaCount }}
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc
        image: "{{ .Values.grpc.image.repository }}:{{ .Values.grpc.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.grpc.service.port }}

        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}

        readinessProbe:
          exec:
            command:
              - grpc_health_probe
              - -addr=localhost:50051
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          exec:
            command:
              - grpc_health_probe
              - -addr=localhost:50051
          initialDelaySeconds: 30
          periodSeconds: 10