apiVersion: v2
name: boilerplate-webapp
description: A helm chart for deploying boilerplate-webapp with frontend, backend, and grpc
version: 0.1.0  # Helm chart version
appVersion: "0.0.6-SNAPSHOT" # Application version
