frontend:
  image:
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: false
    hosts:
      - host: frontend.mycompany.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: frontend-tls
        hosts:
          - frontend.mycompany.com

backend:
  image:
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP

grpc:
  image:
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
