name: Dev Docker Backend Push

on:
  push:
    branches:
      - development
    paths:
      - 'backend/**'
      - 'docker/backend.dockerfile'

jobs:
  call-prod:
    uses: ./.github/workflows/template_dev_docker.yml
    with:
      context: .
      dockerfile: docker/backend.dockerfile
      image_name: backend
