name: Dev Docker Frontend Push

on:
  push:
    branches:
      - development
    paths:
      - 'frontend/**'
      - 'docker/frontend.dockerfile'

jobs:
  call-prod:
    uses: ./.github/workflows/template_dev_docker.yml
    with:
      context: .
      dockerfile: docker/frontend.dockerfile
      image_name: frontend