name: Dev Docker gRPC Push

on:
  push:
    branches:
      - development
    paths:
      - 'grpc/**'
      - 'docker/grpc.dockerfile'

jobs:
  call-prod:
    # Calls a production-specific reusable workflow
    uses: ./.github/workflows/template_dev_docker.yml
    with:
      context: .
      dockerfile: docker/grpc.dockerfile
      image_name: grpc