name: Feat CI gRPC PR

on:
  pull_request:
    branches:
      - development
    paths:
      - 'grpc/**'

jobs:     
  build-and-integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: grpc
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: grpc/go.sum
    
      - name: Download dependencies
        run: go mod tidy
      
      - name: Build gRPC Server
        run: make build-server

      - name: Run integration tests
        run: make test-integration