name: Feat Docker gRPC Push

on:
  push:
    branches-ignore:
      - main
      - 'release-*.*.*'
      - development
    paths:
      - 'docker/grpc.dockerfile'
      - 'grpc/**'
  
jobs:
  call-docker:
    uses: ./.github/workflows/template_feat_docker.yml
    with:
      dockerfile: docker/grpc.dockerfile
      context: .
      name: grpc