name: Feat Docker Frontend Push

on:
  push:
    branches-ignore:
      - main
      - 'release-*.*.*'
      - development
    paths:
      - 'docker/frontend.dockerfile'
      - 'frontend/**'
  
jobs:
  call-docker:
    # Reuses shared docker build workflow for feat
    uses: ./.github/workflows/template_feat_docker.yml
    with:
      dockerfile: docker/frontend.dockerfile
      context: .
      name: frontend