name: Feat Docker Backend Push

on:
  push:
    branches-ignore:
      - main
      - 'release-*.*.*'
      - development
    paths:
      - 'docker/backend.dockerfile'
      - 'backend/**'
  
jobs:
  call-docker:
    uses: ./.github/workflows/template_feat_docker.yml
    with:
      dockerfile: docker/backend.dockerfile
      context: .
      name: backend